version: '3.9'
x-env: &env
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  REDIS_URL: redis://redis:6379/1

services:
  izoombies:
    build:
      context: .
      dockerfile: Dockerfile
    command: rails s -b 0.0.0.0 -p 3000
    environment:
      <<: *env
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
    - pg
    - redis
  pg:
    image: postgres:11
    environment:
      <<: *env
    ports:
      - "5434:5432"
    volumes:
    - ./docker/postgres/data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6382:6379"
  sidekiq:
    depends_on:
      - 'pg'
      - 'redis'
    build: .
    command: sidekiq -q default
    volumes:
      - '.:/project'
      - '/project/tmp' # don't mount tmp directory
    environment:
      - REDIS_URL=redis://redis:6379/1