version: '3.9'
x-env: &env
  RAILS_ENV: development
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  REDIS_URL: redis://redis:6379/1

services:
  izoombies:
    build:
      context: .
      dockerfile: Dockerfile
    command:  bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      <<: *env
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    ports:
      - "3000:3000"
    depends_on:
    - pg
    - redis
  pg:
    image: postgres:12.1
    environment:
      <<: *env
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6382:6379"
  sidekiq:
    depends_on:
      - 'izoombies'
      - 'pg'
      - 'redis'
    build:
      context: .
      dockerfile: Dockerfile
    command: sidekiq -q default
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/1
  
volumes:
  gem_cache:
  db_data: