# config/sidekiq_scheduler.yml

default: &default
  active_mailings:
    class: MoveAllSurvivorsJob
    cron: '*/1 * * * *'

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default